name: Elsegundonombre
on:
  workflow_dispatch:
  workflow_call:
jobs:
  With-VPN:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
